# Generated by Django 3.1.3 on 2020-12-15 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_full_name', models.CharField(max_length=100, verbose_name='FISH')),
                ('passport_id', models.CharField(max_length=15, verbose_name='Passport')),
                ('foreign_company', models.CharField(max_length=100, verbose_name='Xorijiy tashkilot nomi')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('citizenship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.citizenship', verbose_name='Fuqaroligi')),
            ],
            options={
                'verbose_name_plural': '      Guest All Information',
            },
        ),
        migrations.CreateModel(
            name='VisaControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Sana')),
                ('guest_come_date', models.DateField(blank=True, null=True, verbose_name='Mehmon keldi')),
                ('guest_back_date', models.DateField(blank=True, null=True, verbose_name='Mehmon keldi')),
                ('guest_living_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Istiqomat qilayotgan manzil')),
                ('guest_living_address_type', models.CharField(blank=True, choices=[('hotel', 'Hotel'), ('flat', 'Kvartira'), ('container', 'Konteyner')], default='flat', max_length=50, null=True, verbose_name='Yashash joyi turi')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='Propiska muddati')),
                ('visa_validate_date', models.DateField(blank=True, null=True, verbose_name='Propiska muddati')),
                ('license_date', models.DateField(blank=True, null=True, verbose_name='Litsenziya muddati')),
                ('possible_leave_date', models.DateField(blank=True, null=True, verbose_name='Ehtimoliy ketish kuni')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Eslatma')),
                ('guest_status', models.CharField(choices=[('come', 'Keldi'), ('leave', 'Qaytib ketti'), ('not_come', 'Kelmadi')], default='come', max_length=50, verbose_name='keldi/Ketdi')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Agent')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.guestinfo', verbose_name='Mehmon')),
            ],
            options={
                'verbose_name_plural': 'Visa Control',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='VisaCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Sana')),
                ('pass_visa_date', models.DateField(blank=True, null=True, verbose_name='Vizaga hujjat topshirilgan sana')),
                ('present_visa_date', models.DateField(blank=True, null=True, verbose_name='Viza taqdim etilgan sana')),
                ('guest_come_date', models.DateField(blank=True, null=True, verbose_name='Mehmon keldi')),
                ('guest_back_date', models.DateField(blank=True, null=True, verbose_name='Mehmon keldi')),
                ('payment_type_to_visa', models.CharField(choices=[('transfer', 'Perechesleniya'), ('transfer_ok', 'Pereches-OK'), ('payed', "To'landi"), ('not_payed', "To'lanmadi")], default='transfer', max_length=50, verbose_name="To'lov statusi")),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Visaga bergan shaxs')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.guestinfo', verbose_name='Mehmon')),
            ],
            options={
                'verbose_name_plural': '    Visa',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='PersonalManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Sana')),
                ('personal_manager', models.CharField(max_length=100, verbose_name="Mas'ul shaxs")),
                ('personal_manager_phone', models.CharField(max_length=15, verbose_name="Mas'ul shaxsning\ntelefon raqami")),
                ('company_offered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.companyoffered', verbose_name='Taklif qiluvchi tashkilot nomi')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.guestinfo', verbose_name='Mehmon')),
            ],
            options={
                'verbose_name_plural': '     Personal Manager',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='OtherDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Sana')),
                ('visa_price_uzs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Bilet narxi (so'mda)")),
                ('visa_price_us', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Bilet narxi ($ da)')),
                ('payment_type_to_visa', models.CharField(choices=[('transfer', 'Perechesleniya'), ('transfer_ok', 'Pereches-OK'), ('payed', "To'landi"), ('not_payed', "To'lanmadi")], default='transfer', max_length=50, verbose_name="To'lov statusi")),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Agent')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.guestinfo', verbose_name='Mehmon')),
            ],
            options={
                'verbose_name_plural': ' Other Documents',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Sana')),
                ('hotel_name', models.CharField(max_length=100, verbose_name='Mehmonxona')),
                ('guest_come_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Mexmon kirgan kuni')),
                ('guest_back_date', models.DateField(blank=True, null=True, verbose_name='Mexmon chiqqan kuni')),
                ('hotel_price_uzs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Narxi (so'mda)")),
                ('hotel_price_us', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Narxi ($ da)')),
                ('payment_type_to_hotel', models.CharField(choices=[('transfer', 'Perechesleniya'), ('transfer_ok', 'Pereches-OK'), ('payed', "To'landi"), ('not_payed', "To'lanmadi")], default='transfer', max_length=50, verbose_name="To'lov statusi")),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Agent')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.guestinfo', verbose_name='Mehmon')),
            ],
            options={
                'verbose_name_plural': '  Hotel',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='AirTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Sana')),
                ('guest_full_name_visa', models.CharField(blank=True, max_length=100, null=True, verbose_name='FISH')),
                ('citizen', models.CharField(choices=[('foreign', 'Ne Rezident'), ('local', 'Rezident')], default='foreign', max_length=50, verbose_name='Fuqaroligi')),
                ('trip_goal', models.CharField(blank=True, default='Muzokaralar uchun', max_length=255, null=True, verbose_name='Safar maqsadi')),
                ('flight', models.CharField(max_length=20, verbose_name='Reys')),
                ('flight_come_date', models.DateField(blank=True, null=True, verbose_name='Kelgan reys')),
                ('flight_back_date', models.DateField(blank=True, null=True, verbose_name='Qaytib ketgan reys')),
                ('ticket_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Bilet narxi')),
                ('payment_type_to_ticket', models.CharField(choices=[('transfer', 'Perechesleniya'), ('transfer_ok', 'Pereches-OK'), ('payed', "To'landi"), ('not_payed', "To'lanmadi")], default='transfer', max_length=50, verbose_name="To'lov statusi")),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.carrier', verbose_name='Aviatashuvchi')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.country', verbose_name='Davlati')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Agent')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.guestinfo', verbose_name='Mehmon')),
            ],
            options={
                'verbose_name_plural': '   Air Ticket',
                'ordering': ('date',),
            },
        ),
    ]
