# Generated by Django 3.0 on 2021-02-03 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_full_name', models.CharField(max_length=100, verbose_name='FISH')),
                ('passport_id', models.CharField(max_length=15, verbose_name='Passport')),
                ('foreign_company', models.CharField(max_length=100, verbose_name='Xorijiy tashkilot nomi')),
                ('created_date', models.DateTimeField(blank=True, null=True, verbose_name='Sana')),
                ('citizenship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Citizenship', verbose_name='Fuqaroligi')),
            ],
            options={
                'verbose_name_plural': '1. Guest All Information',
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='VisaControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Sana')),
                ('guest_come_date', models.DateField(blank=True, null=True, verbose_name='Mehmon keldi')),
                ('guest_back_date', models.DateField(blank=True, null=True, verbose_name='Mehmon ketdi')),
                ('guest_living_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Istiqomat qilayotgan manzil')),
                ('guest_living_address_type', models.CharField(blank=True, choices=[('hotel', 'Hotel'), ('flat', 'Kvartira'), ('container', 'Konteyner')], default='flat', max_length=50, null=True, verbose_name='Yashash joyi turi')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='Propiska muddati')),
                ('visa_validate_date', models.DateField(blank=True, null=True, verbose_name='Visa amal qilish muddati')),
                ('license_date', models.DateField(blank=True, null=True, verbose_name='Litsenziya muddati')),
                ('possible_leave_date', models.DateField(blank=True, null=True, verbose_name='Ehtimoliy ketish kuni')),
                ('visa_days', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kunlar soni')),
                ('guest_status', models.CharField(choices=[('come', 'Keldi'), ('leave', 'Qaytib ketti'), ('not_come', 'Kelmadi')], default='come', max_length=50, verbose_name='keldi/Ketdi')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Agent')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.GuestInfo', verbose_name='Mehmon')),
            ],
            options={
                'verbose_name_plural': '7. Visa Control',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='VisaCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Sana')),
                ('pass_visa_date', models.DateField(blank=True, null=True, verbose_name='Vizaga hujjat topshirilgan sana')),
                ('present_visa_date', models.DateField(blank=True, null=True, verbose_name='Viza taqdim etilgan sana')),
                ('guest_come_date', models.DateField(blank=True, null=True, verbose_name='Mehmon keldi')),
                ('guest_back_date', models.DateField(blank=True, null=True, verbose_name='Mehmon keldi')),
                ('price', models.FloatField(blank=True, default=300000.0, null=True, verbose_name='Narxi')),
                ('payment_type', models.CharField(choices=[('transfer', 'Perechesleniya'), ('transfer_ok', 'Pereches-OK'), ('payed', "To'landi"), ('not_payed', "To'lanmadi")], default='transfer', max_length=50, verbose_name="To'lov statusi")),
                ('visa_days', models.CharField(blank=True, max_length=100, null=True, verbose_name='Visa olingan kundan')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Holati')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Agent')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mid', to='tour.GuestInfo', verbose_name='Mehmon')),
            ],
            options={
                'verbose_name_plural': '3. Visa City',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='PersonalManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Sana')),
                ('personal_manager', models.CharField(max_length=100, verbose_name="Mas'ul shaxs")),
                ('personal_manager_phone', models.CharField(max_length=9, verbose_name="Mas'ul shaxsning\ntelefon raqami")),
                ('company_offered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_manager', to='database.CompanyOffered', verbose_name='Taklif qiluvchi tashkilot nomi')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_managers', to='tour.GuestInfo', verbose_name='Mehmon')),
            ],
            options={
                'verbose_name_plural': '2. Personal Manager',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='OtherDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Sana')),
                ('price', models.FloatField(blank=True, null=True, verbose_name="Narxi (so'mda)")),
                ('payment_type', models.CharField(choices=[('transfer', 'Perechesleniya'), ('transfer_ok', 'Pereches-OK'), ('payed', "To'landi"), ('not_payed', "To'lanmadi")], default='transfer', max_length=50, verbose_name="To'lov statusi")),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Agent')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='others', to='tour.GuestInfo', verbose_name='Mehmon')),
            ],
            options={
                'verbose_name_plural': '6. Other Documents',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Sana')),
                ('hotel_name', models.CharField(max_length=100, verbose_name='Mehmonxona')),
                ('guest_come_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Mexmon kirgan kuni')),
                ('guest_back_date', models.DateField(blank=True, null=True, verbose_name='Mexmon chiqqan kuni')),
                ('price', models.FloatField(blank=True, null=True, verbose_name="Narxi (so'mda)")),
                ('hotel_days', models.CharField(blank=True, max_length=100, null=True, verbose_name='Yashagan kunlar')),
                ('payment_type', models.CharField(choices=[('transfer', 'Perechesleniya'), ('transfer_ok', 'Pereches-OK'), ('payed', "To'landi"), ('not_payed', "To'lanmadi")], default='transfer', max_length=50, verbose_name="To'lov statusi")),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Agent')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='tour.GuestInfo', verbose_name='Mehmon')),
            ],
            options={
                'verbose_name_plural': '5. Hotel',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='AirTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Sana')),
                ('guest_full_name_visa', models.CharField(blank=True, max_length=100, null=True, verbose_name='FISH')),
                ('citizen', models.CharField(choices=[('foreign', 'Ne Rezident'), ('local', 'Rezident')], default='foreign', max_length=50, verbose_name='Fuqaroligi')),
                ('trip_goal', models.CharField(blank=True, default='Muzokaralar uchun', max_length=255, null=True, verbose_name='Safar maqsadi')),
                ('flight', models.CharField(max_length=20, verbose_name='Reys')),
                ('ticket_office', models.CharField(max_length=100, verbose_name='Aviakassa')),
                ('flight_come_date', models.DateField(blank=True, null=True, verbose_name='Kelgan reys')),
                ('flight_back_date', models.DateField(blank=True, null=True, verbose_name='Ketgan reys')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Bilet narxi')),
                ('payment_type', models.CharField(choices=[('transfer', 'Perechesleniya'), ('transfer_ok', 'Pereches-OK'), ('payed', "To'landi"), ('not_payed', "To'lanmadi")], default='transfer', max_length=50, verbose_name="To'lov statusi")),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Carrier', verbose_name='Aviatashuvchi')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Country', verbose_name='Davlati')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Agent')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airtickets', to='tour.GuestInfo', verbose_name='Mehmon')),
            ],
            options={
                'verbose_name_plural': '4. Air Ticket',
                'ordering': ('-date',),
            },
        ),
    ]
