# Generated by Django 3.1.3 on 2020-12-15 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airticket',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='otherdocument',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='personalmanager',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='visacity',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='visacontrol',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Sana'),
        ),
    ]
