# Generated by Django 3.1.3 on 2020-12-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_auto_20201215_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='airticket',
            name='ticket_office',
            field=models.CharField(default='Aviakassa-1', max_length=100, verbose_name='Aviakassa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='airticket',
            name='flight_back_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ketgan reys'),
        ),
        migrations.AlterField(
            model_name='visacontrol',
            name='visa_validate_date',
            field=models.DateField(blank=True, null=True, verbose_name='Visa amal qilish muddati'),
        ),
    ]
