# Generated by Django 3.1.3 on 2020-12-15 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShengenVisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='FISH')),
                ('shengen_country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Shengen davlati')),
                ('submitted_date', models.DateField(blank=True, null=True, verbose_name='Topshirilgan kun')),
                ('possible_leave_date', models.DateField(blank=True, null=True, verbose_name='Ehtimoliy chiqish kuni')),
                ('company_offered', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.companyoffered', verbose_name='Tashkilot nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visa_city', models.IntegerField(blank=True, default=0, null=True, verbose_name='Visa City')),
                ('registration', models.IntegerField(blank=True, default=0, null=True, verbose_name='Registratsiya')),
                ('prad_visa', models.IntegerField(blank=True, default=0, null=True, verbose_name='Prad/Visa')),
                ('shengen_visa', models.IntegerField(blank=True, default=0, null=True, verbose_name='Shengen Visa')),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Summa')),
                ('company_offered', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.companyoffered', verbose_name='Tashkilot nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='FISH')),
                ('passport_id', models.CharField(blank=True, max_length=15, null=True, verbose_name='Passport')),
                ('citizenship', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fuqaroligi')),
                ('guest_living_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Toliq manzili')),
                ('submitted_date', models.DateField(blank=True, null=True, verbose_name='Topshirilgan sana')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='Propiska muddati')),
                ('visa_date', models.DateField(blank=True, null=True, verbose_name='Visa muddati')),
                ('payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('personal_manager', models.CharField(blank=True, max_length=255, null=True, verbose_name="Mas'ul shaxs")),
                ('company_offered', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.companyoffered', verbose_name='Tashkilot nomi')),
            ],
        ),
        migrations.CreateModel(
            name='PradVisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='FISH')),
                ('passport_id', models.CharField(blank=True, max_length=15, null=True, verbose_name='Passport')),
                ('submitted_address', models.DateField(blank=True, null=True, verbose_name='Topshirilgan manzil')),
                ('submitted_date', models.DateField(blank=True, null=True, verbose_name='Topshirilgan sana')),
                ('taking_date', models.DateField(blank=True, null=True, verbose_name='Olish sana')),
                ('guarantee_letter', models.CharField(blank=True, max_length=100, null=True, verbose_name='Гарантийное письмо')),
                ('visa_over_date', models.DateField(blank=True, null=True, verbose_name='Visa tugash muddati')),
                ('payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Kassa to'lovi")),
                ('company_offered', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.companyoffered', verbose_name='Tashkilot nomi')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='FISH')),
                ('license_submitted_date', models.DateField(blank=True, null=True, verbose_name='Litsensizyaga topshirilgan kun')),
                ('license_over_date', models.DateField(blank=True, null=True, verbose_name='Litsenziya tugash muddati')),
                ('status', models.CharField(choices=[('jarayonda', 'jarayonda'), ('kerakmas', 'kerakmas'), ('ketti', 'ketti'), ('olingan', 'olingan'), ('olish_kerak', 'olish_kerak'), ('otmen', 'otmen'), ('yangi', 'yangi')], default='jarayonda', max_length=50, verbose_name='Holati')),
                ('company_offered', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.companyoffered', verbose_name='Tashkilot nomi')),
            ],
        ),
    ]
