# Generated by Django 3.0 on 2021-02-03 12:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '__first__'),
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Sana')),
                ('position', models.CharField(max_length=100, verbose_name='Pozitsiya')),
            ],
            options={
                'verbose_name_plural': '7. Positions',
            },
        ),
        migrations.CreateModel(
            name='ShengenVisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Sana')),
                ('shengen_country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Shengen davlati')),
                ('submitted_date', models.DateField(blank=True, null=True, verbose_name='Topshirilgan kun')),
                ('possible_leave_date', models.DateField(blank=True, null=True, verbose_name='Ehtimoliy chiqish kuni')),
                ('price', models.FloatField(blank=True, default=400000.0, null=True, verbose_name='Narxi')),
                ('payment_type', models.CharField(choices=[('transfer', 'Perechesleniya'), ('transfer_ok', 'Pereches-OK'), ('payed', "To'landi"), ('not_payed', "To'lanmadi")], default='transfer', max_length=50, verbose_name="To'lov statusi")),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.GuestInfo', verbose_name='FISH')),
            ],
            options={
                'verbose_name_plural': '1. Shengen Visa',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Sana')),
                ('company_offered', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.CompanyOffered', verbose_name='Tashkilot nomi')),
            ],
            options={
                'verbose_name_plural': '5. Reports',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Sana')),
                ('submitted_date', models.DateField(blank=True, null=True, verbose_name='Topshirilgan sana')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='Propiska muddati')),
                ('visa_date', models.DateField(blank=True, null=True, verbose_name='Visa muddati')),
                ('payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price', models.FloatField(blank=True, default=300000.0, null=True, verbose_name='Narxi')),
                ('payment_type', models.CharField(choices=[('transfer', 'Perechesleniya'), ('transfer_ok', 'Pereches-OK'), ('payed', "To'landi"), ('not_payed', "To'lanmadi")], default='transfer', max_length=50, verbose_name="To'lov statusi")),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regs', to='tour.GuestInfo', verbose_name='FISH')),
            ],
            options={
                'verbose_name_plural': '3. Registration',
            },
        ),
        migrations.CreateModel(
            name='PradVisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Sana')),
                ('submitted_address', models.DateField(blank=True, null=True, verbose_name='Topshirilgan manzil')),
                ('submitted_date', models.DateField(blank=True, null=True, verbose_name='Topshirilgan sana')),
                ('taking_date', models.DateField(blank=True, null=True, verbose_name='Olish sana')),
                ('guarantee_letter', models.CharField(blank=True, max_length=100, null=True, verbose_name='Гарантийное письмо')),
                ('visa_over_date', models.DateField(blank=True, null=True, verbose_name='Visa tugash muddati')),
                ('price', models.FloatField(blank=True, default=300000.0, null=True, verbose_name='Narxi')),
                ('payment_type', models.CharField(choices=[('transfer', 'Perechesleniya'), ('transfer_ok', 'Pereches-OK'), ('payed', "To'landi"), ('not_payed', "To'lanmadi")], default='transfer', max_length=50, verbose_name="To'lov statusi")),
                ('payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Kassa to'lovi")),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prad_visas', to='tour.GuestInfo', verbose_name='FISH')),
            ],
            options={
                'verbose_name_plural': '4. PradVisa',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Sana')),
                ('license_submitted_date', models.DateField(blank=True, null=True, verbose_name='Litsensizyaga topshirilgan kun')),
                ('license_over_date', models.DateField(blank=True, null=True, verbose_name='Litsenziya tugash muddati')),
                ('status', models.CharField(choices=[('jarayonda', 'jarayonda'), ('kerakmas', 'kerakmas'), ('ketti', 'ketti'), ('olingan', 'olingan'), ('olish_kerak', 'olish_kerak'), ('otmen', 'otmen'), ('yangi', 'yangi')], default='jarayonda', max_length=50, verbose_name='Holati')),
                ('price', models.FloatField(blank=True, default=600000.0, null=True, verbose_name='Narxi')),
                ('payment_type', models.CharField(choices=[('transfer', 'Perechesleniya'), ('transfer_ok', 'Pereches-OK'), ('payed', "To'landi"), ('not_payed', "To'lanmadi")], default='transfer', max_length=50, verbose_name="To'lov statusi")),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='tour.GuestInfo', verbose_name='FISH')),
            ],
            options={
                'verbose_name_plural': '2. Licence',
            },
        ),
        migrations.CreateModel(
            name='Chief',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Sana')),
                ('name', models.CharField(max_length=100, verbose_name='FISH')),
                ('passport', models.CharField(blank=True, max_length=9, null=True, verbose_name='Passport')),
                ('zagran_visa', models.DateField(blank=True, null=True, verbose_name='Zagran passport sana')),
                ('other_visa', models.DateField(blank=True, null=True, verbose_name='Bohsqa visa')),
                ('visa_img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='visa rasmi')),
                ('company_offered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.CompanyOffered', verbose_name='Tashkilot')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Position', verbose_name='Pazitsiyasi')),
            ],
            options={
                'verbose_name_plural': '6. Chiefs',
                'ordering': ('name',),
            },
        ),
    ]
