# Generated by Django 3.1.3 on 2020-12-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Aviatashuvchi')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Tizimga iritilgan sana')),
            ],
        ),
        migrations.CreateModel(
            name='Citizenship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenship', models.CharField(max_length=50, verbose_name='Fuqaroligi')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Tizimga iritilgan sana')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyOffered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Taklif qiluvchi tashkilot nomi')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Tizimga iritilgan sana')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, verbose_name='Davlat')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Tizimga iritilgan sana')),
            ],
        ),
    ]
