# Generated by Django 3.0 on 2021-02-03 12:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Sana')),
                ('name', models.CharField(max_length=100, verbose_name='Aviatashuvchi')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Tizimga iritilgan sana')),
            ],
            options={
                'verbose_name_plural': '2. Carrier',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Citizenship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Sana')),
                ('citizenship', models.CharField(max_length=50, verbose_name='Fuqaroligi')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Tizimga iritilgan sana')),
            ],
            options={
                'verbose_name_plural': '3. Citizenship',
                'ordering': ('citizenship',),
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Sana')),
                ('country', models.CharField(max_length=100, verbose_name='Davlat')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Tizimga iritilgan sana')),
            ],
            options={
                'verbose_name_plural': '1. Country',
                'ordering': ('country',),
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '4. Department',
            },
        ),
        migrations.CreateModel(
            name='CompanyOffered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Sana')),
                ('company_name', models.CharField(max_length=255, verbose_name='Taklif qiluvchi tashkilot nomi')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Tizimga iritilgan sana')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Department')),
            ],
            options={
                'verbose_name_plural': '5. CompanyOffered',
                'ordering': ('company_name',),
            },
        ),
    ]
